services:
  server:
    env_file: ".env"
    build: ./
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    ports: ["5000:5000"]
    volumes: ["./:/app"]
  postgres:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
