services:
  server:
    env_file: ".env"
    build: ./
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports: ["8000:8000"]
    volumes: ["./:/app"]
    networks:
      network:
        ipv4_address: 10.5.0.4
  postgres:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 10.5.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
